#!/usr/bin/env python3
"""Generate a PR comment body pointing to the relevant CI troubleshooting section.

Called by the post-pr-feedback job in quality.yml when a CI lane fails.
Produces a Markdown file suitable for posting as a PR comment via `gh` CLI.

Usage:
    python scripts/generate_pr_comment.py \\
        --job quality-fast \\
        --run-url https://github.com/DeepPal/gas_sensing/actions/runs/12345 \\
        --output output/test-results/pr-comment.md
"""

from __future__ import annotations

import argparse
from pathlib import Path

# Map CI job names → (section title in CI_TROUBLESHOOTING.md, anchor fragment)
_TROUBLESHOOTING_MAP: dict[str, tuple[str, str]] = {
    "quality-fast": (
        "Quality Gates Failed",
        "#1-quality-gates-failed",
    ),
    "workflow-hygiene": (
        "Quality Gates Failed",
        "#1-quality-gates-failed",
    ),
    "reliability": (
        "Reliability Lane Issues",
        "#3-reliability-lane-issues",
    ),
    "security": (
        "Security Gates Failed",
        "#2-security-gates-failed",
    ),
    "docker-build": (
        "Docker Build Failed",
        "#5-docker-build-failed",
    ),
    "release": (
        "Release Workflow Issues",
        "#4-release-workflow-issues",
    ),
}

_DOCS_BASE = (
    "https://github.com/DeepPal/gas_sensing/blob/main/docs/guides/CI_TROUBLESHOOTING.md"
)
_CHECKLIST = {
    "quality-fast": [
        "Run `ruff check . --select E9,F63,F7,F82` locally and fix all errors",
        "Run `mypy src --no-site-packages --ignore-missing-imports --disable-error-code import-untyped`",
        "Run `pytest -q --tb=short -m \"not reliability\"` until green",
        "Push the fixes -- do **not** add `continue-on-error` workarounds",
    ],
    "reliability": [
        "Run `pytest -q --tb=short -m reliability --durations=20` locally",
        "Check `output/test-results/reliability-summary.md` for slow or failed tests",
        "Check `output/test-results/flaky-report.md` — test may be pre-existing flaky",
        "If flaky, add `@pytest.mark.xfail(strict=False)` and file a tracking issue",
    ],
    "workflow-hygiene": [
        "Run `python scripts/validate_workflows.py` locally",
        "Ensure `if:` expressions do **not** wrap secrets in `${{ }}`",
        "Run actionlint locally: `actionlint .github/workflows/*.yml`",
    ],
    "security": [
        "Run `pip-audit` locally: `pip install pip-audit && pip-audit`",
        "Run `bandit -r src gas_analysis dashboard -ll`",
        "Check `dependency-review` output for new transitive vulnerable packages",
    ],
    "docker-build": [
        "Run `docker build -t spectraagent:test .` locally",
        "Check `COPY` paths in Dockerfile match repo structure after recent moves",
    ],
    "release": [
        "Run `python scripts/check_artifact_hygiene.py --dist-dir dist`",
        "Run `python scripts/verify_release_manifest.py --dist-dir dist --manifest sha256sums.txt`",
        "Ensure `spectraagent.__version__` matches the git tag",
    ],
}


def _checklist_for(job: str) -> list[str]:
    return _CHECKLIST.get(job, ["See the CI troubleshooting guide for details."])


def _docs_link(job: str) -> str:
    section_title, anchor = _TROUBLESHOOTING_MAP.get(
        job,
        ("CI Troubleshooting Guide", ""),
    )
    return f"[{section_title}]({_DOCS_BASE}{anchor})"


def _build_comment(job: str, run_url: str) -> str:
    checklist_items = "\n".join(f"- [ ] {item}" for item in _checklist_for(job))
    docs_link = _docs_link(job)
    job_display = f"`{job}`"
    return f"""> [!NOTE]
> **CI failed on {job_display}** - here are fast recovery steps.

## Quick Troubleshooting Checklist

{checklist_items}

## More Detail

Full runbook: {docs_link}

Workflow run: {run_url}

---
*This comment was auto-generated by the CI troubleshooting bot. If it's wrong, file an issue.*
"""


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--job",
        required=True,
        help="Name of the CI job that failed",
    )
    parser.add_argument(
        "--run-url",
        default="(run URL not provided)",
        help="URL of the workflow run",
    )
    parser.add_argument(
        "--output",
        required=True,
        help="Path to write the markdown comment body",
    )
    args = parser.parse_args()

    comment = _build_comment(job=args.job, run_url=args.run_url)
    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(comment, encoding="utf-8")
    print(f"[pr-comment] Comment body written to {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
